/* automatically generated from MyConfig */
#include "/home/wolf/bam2011/src/main/amr/bam_amr.h"
#include "/home/wolf/bam2011/src/utility/AwA/bam_AwA.h"
#include "/home/wolf/bam2011/src/utility/boundary/bam_boundary.h"
#include "/home/wolf/bam2011/src/utility/checkpoint/bam_checkpoint.h"
#include "/home/wolf/bam2011/src/utility/elliptic/iterative/bam_iterative.h"
#include "/home/wolf/bam2011/src/utility/elliptic/multigrid/bam_multigrid.h"
#include "/home/wolf/bam2011/src/utility/evolve/bam_evolve.h"
#include "/home/wolf/bam2011/src/utility/interpolate/bam_interpolate.h"
#include "/home/wolf/bam2011/src/utility/output/bam_output.h"
#include "/home/wolf/bam2011/src/utility/FiniteDiff/bam_FiniteDiff.h"
#include "/home/wolf/bam2011/src/utility/NumericUtils/bam_NumericUtils.h"
#include "/home/wolf/bam2011/src/projects/scalarwaves/bam_scalarwaves.h"
#include "/home/wolf/bam2011/src/projects/adm/bam_adm.h"
#include "/home/wolf/bam2011/src/projects/bssn/bam_bssn.h"
#include "/home/wolf/bam2011/src/projects/punctures/bam_punctures.h"
#include "/home/wolf/bam2011/src/projects/Gauge/bam_Gauge.h"
#include "/home/wolf/bam2011/src/projects/Invariants/bam_Invariants.h"
#include "/home/wolf/bam2011/src/projects/ADM_mass/bam_ADM_mass.h"
#include "/home/wolf/bam2011/src/projects/BHfiller/bam_BHfiller.h"
#include "/home/wolf/bam2011/src/projects/AHmod/bam_AHmod.h"
#include "/home/wolf/bam2011/src/projects/BBHdataReader/bam_BBHdataReader.h"
#include "/home/wolf/bam2011/src/main/bampi/bam_bampi.h"
#include "/home/wolf/bam2011/src/main/main/bam_main.h"
void bam_evolve_final();
void bam_adm_final();
void bam_main_final();
void bam_amr();
void bam_AwA();
void bam_boundary();
void bam_checkpoint();
void bam_iterative();
void bam_multigrid();
void bam_evolve();
void bam_interpolate();
void bam_output();
void bam_FiniteDiff();
void bam_NumericUtils();
void bam_scalarwaves();
void bam_adm();
void bam_bssn();
void bam_punctures();
void bam_Gauge();
void bam_Invariants();
void bam_ADM_mass();
void bam_BHfiller();
void bam_AHmod();
void bam_BBHdataReader();
void bam_bampi();
void bam_main();
